"""empty message

Revision ID: e0a995c67517
Revises: ed64c45000cb
Create Date: 2016-11-30 02:01:31.745267

"""

# revision identifiers, used by Alembic.
revision = 'e0a995c67517'
down_revision = 'ed64c45000cb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('response', sa.String(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('response_time', sa.Integer(), nullable=True),
    sa.Column('errors', sa.Integer(), nullable=True),
    sa.Column('pauses', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response')
    ### end Alembic commands ###
