"""empty message

Revision ID: ed64c45000cb
Revises: a8ccb4aecc50
Create Date: 2016-11-25 11:58:10.108162

"""

# revision identifiers, used by Alembic.
revision = 'ed64c45000cb'
down_revision = 'a8ccb4aecc50'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['username'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    ### end Alembic commands ###
